// Auth Action Types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Passwordless Auth Action Types
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

export const RESTORE_AUTH = 'RESTORE_AUTH';

// Admin Action Types
export const FETCH_ADMIN_STATS_REQUEST = 'FETCH_ADMIN_STATS_REQUEST';
export const FETCH_ADMIN_STATS_SUCCESS = 'FETCH_ADMIN_STATS_SUCCESS';
export const FETCH_ADMIN_STATS_FAILURE = 'FETCH_ADMIN_STATS_FAILURE';

// Admin chef management actions
export const FETCH_CHEFS_REQUEST = 'FETCH_CHEFS_REQUEST';
export const FETCH_CHEFS_SUCCESS = 'FETCH_CHEFS_SUCCESS';
export const FETCH_CHEFS_FAILURE = 'FETCH_CHEFS_FAILURE';

export const FETCH_CHEF_DETAIL_REQUEST = 'FETCH_CHEF_DETAIL_REQUEST';
export const FETCH_CHEF_DETAIL_SUCCESS = 'FETCH_CHEF_DETAIL_SUCCESS';
export const FETCH_CHEF_DETAIL_FAILURE = 'FETCH_CHEF_DETAIL_FAILURE';

export const CREATE_PLATE_FOR_CHEF_REQUEST = 'CREATE_PLATE_FOR_CHEF_REQUEST';
export const CREATE_PLATE_FOR_CHEF_SUCCESS = 'CREATE_PLATE_FOR_CHEF_SUCCESS';
export const CREATE_PLATE_FOR_CHEF_FAILURE = 'CREATE_PLATE_FOR_CHEF_FAILURE';

// User Action Types
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

// Plats Action Types
export const FETCH_PLATS_REQUEST = 'FETCH_PLATS_REQUEST';
export const FETCH_PLATS_SUCCESS = 'FETCH_PLATS_SUCCESS';
export const FETCH_PLATS_FAILURE = 'FETCH_PLATS_FAILURE';

// Add more action types as needed
